#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'smach-napp==0.8.0','console_scripts','smach_nav2_client'
__requires__ = 'smach-napp==0.8.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('smach-napp==0.8.0', 'console_scripts', 'smach_nav2_client')()
    )
