name: Build and Publish Docker

on:
  pull_request:
    types:
      - opened

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}

      - name: Set branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_HEAD_REF##*/}"
        id: set_branch

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/ml-devel/Dockerfile
          push: true
          tags: |
            ghcr.io/itomasaki/mlr/ml-devel:${{steps.set_branch.outputs.branch}}
